//EEPROM Memory locations
#define LED_STORE 0
#define WT_STORE 1
#define R_STORE 2
#define G_STORE 3
#define B_STORE 4

#define MODE_RAINBOW 1
#define MODE_RAINBOW_CYCLE 2
#define MODE_RAINBOW_THEATRE 3
#define MODE_THEATRE_WHITE 4
#define MODE_THEATRE_RED 5
#define MODE_THEATRE_GREEN 6
#define MODE_THEATRE_BLUE 7
#define MODE_RED 8
#define MODE_GREEN 9
#define MODE_BLUE 10
#define MODE_CUSTOM 11
#define MODE_TURNOFF 12
